export const LAYOUT_GET_BREADCRUME = 'LAYOUT_GET_BREADCRUME'
export const LAYOUT_SET_BREADCRUME = 'LAYOUT_SET_BREADCRUME'

export const GLOBAL_SET_USERNAME = 'GLOBAL_SET_USERNAME'
export const GLOBAL_GET_USERNAME = 'GLOBAL_GET_USERNAME'
export const GLOBAL_RESET_USERNAME = 'GLOBAL_RESET_USERNAME'
export const GLOBAL_CALL_DETAIL = 'GLOBAL_CALL_DETAIL'
